---
# syntax - https://github.com/redhat-plumbers-in-action/advanced-issue-labeler#policy

policy:
  - template: [ bug_report.yml, feature_request.yml ]
    section:
      - id: [ unity-version ]
        block-list: [ Other ]
        label:
          - name: "Unity 2022"
            keys: [ '2022.3.22f1' ]

          - name: "Unity 2019"
            keys: [ '2019.4.31f1' ]
