blank_issues_enabled: false
contact_links:
    - name: Lastation Discord Server
      url: https://discord.gg/lastation
      about: Join our official Discord Server for support, questions & discussion.
