name: Feature Request
description: Suggest an improvement to the project
labels: [ "Suggestion 💡" ]
assignees: [ KuryKat ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        
        ## Before making a suggestion please:
        
        - Check for similar suggestions in the **Issues & Discussions sections**.

  - type: input
    id: version
    attributes:
      label: "The project version that you checked that didn't have the feature you are asking for"
      description: |
        "'Latest' is not a valid answer, please write the exact version number."
        If this is not the most recently released upstream version, then please check first if it has that feature already.
    validations:
      required: true

  - type: dropdown
    id: unity-version
    attributes:
      label: "Which Unity Version are you using?"
      multiple: false
      options:
        - '2022.3.22f1'
        - '2019.4.31f1'
        - 'Other'
    validations:
      required: true
  
  - type: input
    id: other-unity-version
    attributes:
      label: "Other Unity Version"
      description: "If you answered 'Other' above, please specify the exact Unity version."
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Describe your suggestion
      description: What would you like added/changed?
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why would you like this added/changed?
    validations:
      required: true
