name: Suggestion
description: Suggest a change or addition to the project
labels: [Suggestion]
body:
  - type: markdown
    attributes:
      value: |
      
        ## Before making a suggestion please:
        
        - Check for similar suggestions in the **Issues & Discussions sections**.

  - type: textarea
    id: description
    attributes:
      label: Describe your suggestion
      description: What would you like added/changed?
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why would you like this added/changed?
    validations:
      required: true
